config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :articles
  end

  resources :articles do
    resources :comments
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, :body, presence: true, length: { minimum: 5 }
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, presence: true, on: :create
  validates :email, uniqueness: true, on: :create
  has_secure_password
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end


  def new
    redirect_to login_path unless current_user
    @article = Article.new()
    @article.user = current_user

  end

  def create
    redirect_to login_path unless current_user
    @article = Article.new(params.require(:article).permit(:title, :body))
    @article.user = current_user

    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    redirect_to login_path unless current_user
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
    @user = @article.user
    @comments = @article.comments
    @comment = Comment.new()

  end

  def update
    redirect_to login_path unless current_user
    redirect_to article_path
  end

  def delete
    redirect_to login_path unless current_user
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @article = Article.find(params[:article_id])
    @comment = Comment.new()
  end

  def create
    redirect_to login_path unless current_user
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.user = current_user
    @comment.article = Article.find(params[:article_id])

    if @comment.save
      redirect_to article_path(@comment.article)
    else
      render "article/#{params[:article_id]}"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to 'sessions/login'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(params.require(:user).permit(:email,:password))
    if @user.save
      session[:user_id] = @user.id
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  # post users/:id
  def update
    redirect_to user_path
  end

  # delete users/:id
  def delete
    @user = User.find(params[:id])
    @user.destroy
    redirect_to articles_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
<table>
  <tr>
    <td><%= f.label :title %></td>
    <td><%= f.text_field :title%></td>
  </tr>
  <tr>
    <td><%= f.label :body %></td>
    <td><%= f.text_area :body%></td>
  </tr>
  <tr>
    <td><%= f.submit %></td>
  </tr>
</table>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit this Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<%= link_to "New Article", new_article_path %>

<% @articles.each do |article| %>
  <ul>
    <li><%= link_to article.title, article_path(article) %></li>
  </ul>
<% end %>

app/views/articles/new.html.erb
<h1>Post a new Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%=@article.title%></h1>
<hr>
<p>Author: <%= @user.email %></p>
<p><%=@article.body%></p>

<% if current_user %>
  <% if current_user == @user %>
  <p><%= link_to 'Edit', edit_article_path(@article) %> | <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>

<hr>
  <%= render 'comments/form' %>

<% end %>

app/views/comments/_form.html.erb
<%= form_for [@article, @comment] do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/new.html.erb
<h1>Add a new comment!</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>H4X0R N3W5</h1>
    <nav>
    <%= link_to 'Home', root_path %> |
    <% if current_user %>
      <%= link_to 'My profile', user_path(current_user) %> |
      <%= link_to 'Logout', logout_path %>
    <% else %>
      <%= link_to 'Join', new_user_path %> |
      <%= link_to 'Login', login_path %>
    <% end %>
    </nav>
  </header>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.email %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><div class="user_wrapper"><%= link_to user.email, user_path(user) %></div></li>
    <p><%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></p>

  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%=@user.email%></h1>

<ul>
  <% @articles.each do |article| %>
      <div class="article-wrappper">
        <li><%= link_to article.title, articles_path(article) %></li>


      </div>
  <% end %>
</ul>

    <p><%= link_to 'Edit', edit_user_path(@user) %> | <%= link_to 'Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %></p>